using System.Reflection;
using System.Runtime.InteropServices;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using ObjektRT.Core.Model;

namespace ObjectRT.VM;

/// <summary>
/// C#-emitting JIT backend. Each <see cref="CompiledFunction"/> is translated
/// to C# source, compiled with Roslyn, and returned as a delegate. Functions
/// containing unsupported opcodes fall back to the interpreter automatically.
/// </summary>
public sealed class ReflectionJit : ExecutorBase
{
    private readonly Dictionary<uint, Func<IExecutor, Value[], Value>> _compiled = new();
    private Interpreter? _fallback;

    /// <summary>
    /// When non-null, every module compiled by <see cref="ReflectionJit"/>
    /// emits its generated C# source to this directory as
    /// <c>{ModuleName}.ObjectRT.g.cs</c>. Useful for debugging the code-gen
    /// output, or abusing the JIT as an ObjectIL→C# compiler.
    /// </summary>
    public static string? EmitDir { get; set; }

    /// <summary>
    /// When non-null, compiled assemblies are cached to this directory as
    /// <c>{hash}.dll</c> and reloaded on subsequent runs. The hash covers
    /// all function bytecode + the string table, so recompilation via Roslyn
    /// only happens when the module actually changes.
    /// </summary>
    public static string? CacheDir { get; set; }

    public ReflectionJit(CompiledModule mod) : base(mod) { Task.Run(CompileAll); }

    public override void Reset(bool clearHeap = false, bool clearStatics = false)
    {
        if (clearHeap) Heap.Clear();
        if (clearStatics) Array.Fill(StaticFields, Value.Nil());
    }

    public override Result<Value> RunFunction(uint funcIdx, Value[] args)
    {
        CallCounts?.AddOrUpdate(Mod.Functions[(int)funcIdx].DebugName, 1, (_, c) => c + 1);
        if (_compiled.TryGetValue(funcIdx, out var fn))
        {
            try { return fn(this, args); }
            catch (Exception ex) { return new VmError(VmErrorKind.RuntimeError, ex.Message); }
        }
        _fallback ??= new Interpreter(Mod) { NativeCallHandler = NativeCallHandler };
        return _fallback.RunFunction(funcIdx, args);
    }

    /// <summary>Whether a specific function has been compiled yet.</summary>
    public bool IsCompiled(uint funcIdx) => _compiled.ContainsKey(funcIdx);

    // ── Compilation ──────────────────────────────────────────────

    private void CompileAll()
    {
        var methods = new List<(uint idx, CompiledFunction func, string methodSrc)>();
        foreach (var func in Mod.Functions)
        {
            if (IsCompilable(func))
                methods.Add((func.SelfIndex, func, GenerateMethod(func, Mod)));
        }
        if (methods.Count == 0) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using ObjectRT.VM;");
        sb.AppendLine("namespace ObjectRT.Generated {");
        sb.AppendLine("public static class GeneratedModule {");
        foreach (var (_, _, src) in methods)
            sb.Append(src);
        sb.AppendLine("}}");

        var fullSource = sb.ToString();

        // Optional: dump generated C# to disk (debug / compiler abuse).
        if (EmitDir is not null)
        {
            try
            {
                Directory.CreateDirectory(EmitDir);
                var emitPath = Path.Combine(EmitDir, $"{SafeModuleName(Mod.Functions[0]?.DebugName ?? "module")}.ObjectRT.g.cs");
                File.WriteAllText(emitPath, fullSource);
            }
            catch { /* best-effort */ }
        }

        // ── Disk cache: load cached assembly or compile + save ────
        var hash = ComputeModuleHash();
        Assembly? asm = null;

        if (CacheDir is not null)
        {
            try
            {
                Directory.CreateDirectory(CacheDir);
                var cachePath = Path.Combine(CacheDir, $"{hash}.dll");
                if (File.Exists(cachePath))
                {
                    asm = Assembly.Load(File.ReadAllBytes(cachePath));
                }
                else
                {
                    asm = CompileAssembly(fullSource);
                    if (s_lastEmittedBytes is not null)
                        File.WriteAllBytes(cachePath, s_lastEmittedBytes);
                }
            }
            catch
            {
                // Disk failure or stale cache — fall through to in-memory compile.
                asm ??= CompileAssembly(fullSource);
            }
        }
        else
        {
            asm = CompileAssembly(fullSource);
        }

        if (asm == null) return;

        var genType = asm.GetType("ObjectRT.Generated.GeneratedModule");
        if (genType == null) return;

        foreach (var (idx, func, _) in methods)
        {
            var method = genType.GetMethod(SafeMethodName(func.DebugName), BindingFlags.Public | BindingFlags.Static);
            if (method != null)
                _compiled[idx] = (Func<IExecutor, Value[], Value>)Delegate.CreateDelegate(
                    typeof(Func<IExecutor, Value[], Value>), method);
        }
    }

    // ── Opcode support ───────────────────────────────────────────

    private static bool IsCompilable(CompiledFunction func)
    {
        var code = func.Code;
        uint pc = 0;
        while (pc < code.Length)
        {
            ushort op = Interpreter.ReadOpcode(code, ref pc);
            if (IsUnsupported(op)) return false;
            SkipOperand(code, ref pc, op);
            if ((Opcode)op == Opcode.Ret) return true;
        }
        return true;
    }

    private static bool IsUnsupported(ushort op) => (Opcode)op switch
    {
        // Structured exception handling and loop-control flow remain unsupported
        // because they require frame/state management the JIT doesn't model yet.
        Opcode.Try or Opcode.Throw or Opcode.Break or Opcode.Continue => true,
        _ => false,
    };

    // ── C# generation ────────────────────────────────────────────

    private static string GenerateMethod(CompiledFunction func, CompiledModule mod)
    {
        var code = func.Code;
        var sb = new StringBuilder();

        var targets = new HashSet<int>();
        uint pc = 0;
        while (pc < code.Length)
        {
            int pos = (int)pc;
            ushort op = Interpreter.ReadOpcode(code, ref pc);
            if (op is (ushort)Opcode.Br or (ushort)Opcode.Brtrue or (ushort)Opcode.Brfalse)
            {
                int off = Interpreter.ReadI32(code, ref pc);
                targets.Add(pos + ByteSize(op) + 4 + off);
            }
            else SkipOperand(code, ref pc, op);
            if ((Opcode)op == Opcode.Ret) break;
        }

        sb.Append($"public static Value {SafeMethodName(func.DebugName)}(IExecutor e, Value[] args) {{");
        sb.AppendLine();
        sb.AppendLine("    var exec = (ExecutorBase)e;");
        sb.AppendLine($"    var s = new Value[{func.MaxStack + 8}]; int sp = 0;");

        // Emit opcodes
        pc = 0;
        while (pc < code.Length)
        {
            int pos = (int)pc;
            if (targets.Contains(pos))
                sb.AppendLine($"    L_{pos}:");

            ushort op = Interpreter.ReadOpcode(code, ref pc);
            EmitOp(sb, func, mod, code, ref pc, op, targets, pos);
            sb.AppendLine();
            if ((Opcode)op == Opcode.Ret) break;
        }

        sb.AppendLine("    return Value.Nil();");
        sb.AppendLine("    }");
        return sb.ToString();
    }

    private static void EmitOp(StringBuilder sb, CompiledFunction func, CompiledModule mod,
        byte[] code, ref uint pc, ushort op, HashSet<int> targets, int pos)
    {
        switch ((Opcode)op)
        {
            case Opcode.Nop: sb.Append("    // nop"); break;

            case Opcode.LdcI4: case Opcode.Ldc:
                { int v = Interpreter.ReadI32(code, ref pc); sb.Append($"    s[sp++] = Value.FromI4({F(v)});"); break; }
            case Opcode.LdcI8:
                { long v = Interpreter.ReadI64(code, ref pc); sb.Append($"    s[sp++] = Value.FromI8({v}L);"); break; }
            case Opcode.LdcR4:
                { float v = Interpreter.ReadF32(code, ref pc); sb.Append($"    s[sp++] = Value.FromR4({FF(v)}f);"); break; }
            case Opcode.LdcR8:
                { double v = Interpreter.ReadF64(code, ref pc); sb.Append($"    s[sp++] = Value.FromR8({FD(v)}d);"); break; }
            case Opcode.Ldstr:
                { ushort si = Interpreter.ReadU16(code, ref pc); sb.Append($"    s[sp++] = Value.FromStr(e.InternString(\"{CS(mod.GetString(si))}\"));"); break; }

            case Opcode.Ldarg:
                { ushort ai = Interpreter.ReadU16(code, ref pc); sb.Append($"    s[sp++] = args[{ai}];"); break; }
            case Opcode.Starg:
                { ushort ai = Interpreter.ReadU16(code, ref pc); sb.Append($"    args[{ai}] = s[--sp];"); break; }
            case Opcode.Ldloc:
                { ushort li = Interpreter.ReadU16(code, ref pc); sb.Append($"    s[sp++] = args[{func.NumParams + li}];"); break; }
            case Opcode.Stloc:
                { ushort li = Interpreter.ReadU16(code, ref pc); sb.Append($"    args[{func.NumParams + li}] = s[--sp];"); break; }

            case Opcode.Add: sb.Append("    { var b=s[--sp]; var a=s[--sp]; s[sp++]=Interpreter.Arith(a,b,Interpreter.I4Add,Interpreter.I8Add,Interpreter.R4Add,Interpreter.R8Add); }"); break;
            case Opcode.Sub: sb.Append("    { var b=s[--sp]; var a=s[--sp]; s[sp++]=Interpreter.Arith(a,b,Interpreter.I4Sub,Interpreter.I8Sub,Interpreter.R4Sub,Interpreter.R8Sub); }"); break;
            case Opcode.Mul: sb.Append("    { var b=s[--sp]; var a=s[--sp]; s[sp++]=Interpreter.Arith(a,b,Interpreter.I4Mul,Interpreter.I8Mul,Interpreter.R4Mul,Interpreter.R8Mul); }"); break;
            case Opcode.Div: sb.Append("    { var b=s[--sp]; var a=s[--sp]; s[sp++]=Interpreter.Arith(a,b,Interpreter.I4Div,Interpreter.I8Div,Interpreter.R4Div,Interpreter.R8Div); }"); break;
            case Opcode.Rem: sb.Append("    { var b=s[--sp]; var a=s[--sp]; s[sp++]=Interpreter.Arith(a,b,Interpreter.I4Rem,Interpreter.I8Rem,Interpreter.R4Rem,Interpreter.R8Rem); }"); break;
            case Opcode.Neg: sb.Append("    { var v=s[--sp]; s[sp++]=Interpreter.Negate(v); }"); break;

            case Opcode.And: sb.Append("    { int b=s[--sp].I4, a=s[--sp].I4; s[sp++]=Value.FromI4(a&b); }"); break;
            case Opcode.Or:  sb.Append("    { int b=s[--sp].I4, a=s[--sp].I4; s[sp++]=Value.FromI4(a|b); }"); break;
            case Opcode.Xor: sb.Append("    { int b=s[--sp].I4, a=s[--sp].I4; s[sp++]=Value.FromI4(a^b); }"); break;
            case Opcode.Not: sb.Append("    { var v=s[--sp]; s[sp++]=Value.FromI4(~v.I4); }"); break;

            case Opcode.Ceq: sb.Append("    { var b=s[--sp]; var a=s[--sp]; s[sp++]=Value.FromI4(Interpreter.NumericCompare(a,b)==0?1:0); }"); break;
            case Opcode.Cne: sb.Append("    { var b=s[--sp]; var a=s[--sp]; s[sp++]=Value.FromI4(Interpreter.NumericCompare(a,b)!=0?1:0); }"); break;
            case Opcode.Cgt: sb.Append("    { var b=s[--sp]; var a=s[--sp]; s[sp++]=Value.FromI4(Interpreter.NumericCompare(a,b)>0?1:0); }"); break;
            case Opcode.Cge: sb.Append("    { var b=s[--sp]; var a=s[--sp]; s[sp++]=Value.FromI4(Interpreter.NumericCompare(a,b)>=0?1:0); }"); break;
            case Opcode.Clt: sb.Append("    { var b=s[--sp]; var a=s[--sp]; s[sp++]=Value.FromI4(Interpreter.NumericCompare(a,b)<0?1:0); }"); break;
            case Opcode.Cle: sb.Append("    { var b=s[--sp]; var a=s[--sp]; s[sp++]=Value.FromI4(Interpreter.NumericCompare(a,b)<=0?1:0); }"); break;

            case Opcode.Dup:    sb.Append("    { var v=s[sp-1]; s[sp++]=v; }"); break;
            case Opcode.Pop:    sb.Append("    sp--;"); break;
            case Opcode.Ldnull: sb.Append("    s[sp++] = Value.Nil();"); break;

            case Opcode.Ldsfld:
                { ushort fi = Interpreter.ReadU16(code, ref pc); sb.Append($"    s[sp++] = exec.StaticFields[{fi}];"); break; }
            case Opcode.Stsfld:
                { ushort fi = Interpreter.ReadU16(code, ref pc); sb.Append($"    exec.StaticFields[{fi}] = s[--sp];"); break; }

            case Opcode.Call: case Opcode.Callvirt: case Opcode.NativeCall:
            {
                ushort si = Interpreter.ReadU16(code, ref pc);
                ushort argc = Interpreter.ReadU16(code, ref pc);
                string name = mod.GetString(si);
                sb.Append($"    {{ var a=new object?[{argc}];");
                for (int ai = argc - 1; ai >= 0; ai--)
                    sb.Append($"a[{ai}]=e.ValueToObject(s[--sp]);");
                sb.Append($"s[sp++]=e.MarshalValue(e.NativeCallHandler!(\"{CS(name)}\",a)); }}");
                break;
            }

            case Opcode.Ret:
                sb.Append("    return sp > 0 ? s[sp - 1] : Value.Nil();");
                break;

            case Opcode.Br:
                { int off = Interpreter.ReadI32(code, ref pc); sb.Append($"    goto L_{pos + ByteSize(op) + 4 + off};"); break; }
            case Opcode.Brfalse:
                { int off = Interpreter.ReadI32(code, ref pc); sb.Append($"    if (!s[--sp].IsTruthy()) goto L_{pos + ByteSize(op) + 4 + off};"); break; }
            case Opcode.Brtrue:
                { int off = Interpreter.ReadI32(code, ref pc); sb.Append($"    if (s[--sp].IsTruthy()) goto L_{pos + ByteSize(op) + 4 + off};"); break; }

            // ── Object model ───────────────────────────────────

            case Opcode.Newobj:
            {
                ushort ti = Interpreter.ReadU16(code, ref pc);
                sb.Append($"    {{ var _ar = exec.AllocObject({ti}); if (_ar.IsError) return _ar.Error; s[sp++] = Value.FromObj(_ar.Value); }}");
                break;
            }

            case Opcode.Ldfld:
            {
                ushort fi = Interpreter.ReadU16(code, ref pc);
                sb.Append($"    {{ var _o = s[--sp]; uint _h = _o.AsObj(); s[sp++] = MemoryMarshal.Read<Value>(exec.Heap[(int)_h].AsSpan((int){mod.Fields[(int)fi].Offset}, 16)); }}");
                break;
            }

            case Opcode.Stfld:
            {
                ushort fi = Interpreter.ReadU16(code, ref pc);
                sb.Append($"    {{ var _v = s[--sp]; var _o = s[--sp]; uint _h = _o.AsObj(); MemoryMarshal.Write(exec.Heap[(int)_h].AsSpan((int){mod.Fields[(int)fi].Offset}, 16), in _v); }}");
                break;
            }

            // ── Arrays ─────────────────────────────────────────

            case Opcode.Newarr:
            {
                Interpreter.ReadU16(code, ref pc);  // element type (informational)
                sb.Append("    { var _len = s[--sp]; var _arr = new object[_len.I4]; s[sp++] = Value.FromObj(exec.State.InternExternal(_arr)); }");
                break;
            }

            case Opcode.Ldelem:
            {
                sb.Append("    { var _idx = s[--sp]; var _arrV = s[--sp]; var _a = (System.Array)exec.State.GetExternal(_arrV.AsObj()); s[sp++] = e.MarshalValue(_a.GetValue(_idx.I4)); }");
                break;
            }

            case Opcode.Stelem:
            {
                sb.Append("    { var _v = s[--sp]; var _idx = s[--sp]; var _arrV = s[--sp]; var _a = (System.Array)exec.State.GetExternal(_arrV.AsObj()); _a.SetValue(e.ValueToObject(_v), _idx.I4); }");
                break;
            }

            // ── Type ops (no-ops in the dynamic VM) ────────────

            case Opcode.Conv: case Opcode.Castclass: case Opcode.Isinst:
                Interpreter.ReadU16(code, ref pc);  // type index (informational)
                sb.Append("    // conv/cast (no-op in dynamic VM)");
                break;

            // ── Structured control flow (markers — actual branching is br/brtrue/brfalse) ──

            case Opcode.If: case Opcode.While:
            {
                byte ck = code[pc++];
                if (ck == 0x01) pc++;                  // comparison byte
                else if (ck >= 0x02)                  // Expression or Block
                {
                    uint len = Interpreter.ReadU32(code, ref pc);
                    pc += len;
                }
                sb.Append($"    // {(Opcode)op} marker (branching already compiled to br/brtrue/brfalse)");
                break;
            }

            default: sb.Append("    // ??"); break;
        }
    }

    // ── Roslyn ───────────────────────────────────────────────────

    private static int s_asmCounter;
    private static byte[]? s_lastEmittedBytes;

    private static Assembly? CompileAssembly(string source)
    {
        var tree = CSharpSyntaxTree.ParseText(source,
            new CSharpParseOptions(LanguageVersion.Latest));

        var refs = new[]
        {
            typeof(object).Assembly,
            typeof(Value).Assembly,
            typeof(Enumerable).Assembly,
            Assembly.Load("System.Runtime"),
        }.Select(a => MetadataReference.CreateFromFile(a.Location)).ToArray();

        var name = $"ObjectRT_Gen_{s_asmCounter++}";
        var comp = CSharpCompilation.Create(name, new[] { tree }, refs,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary,
                optimizationLevel: OptimizationLevel.Release));

        using var ms = new MemoryStream();
        var result = comp.Emit(ms);
        if (!result.Success)
        {
            var diag = string.Join("\n", result.Diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error));
            Console.Error.WriteLine($"[ReflectionJit] compilation failed:\n{diag}");
            s_lastEmittedBytes = null;
            return null;
        }
        var bytes = ms.ToArray();
        s_lastEmittedBytes = bytes;
        return Assembly.Load(bytes);
    }

    // ── Helpers ──────────────────────────────────────────────────

    private static string SafeMethodName(string n)
    {
        var sb = new StringBuilder();
        foreach (char c in n) sb.Append(char.IsLetterOrDigit(c) || c == '_' ? c : '_');
        return sb.ToString();
    }

    /// <summary>Extract a safe module name from the first function's qualified name.</summary>
    private static string SafeModuleName(string? firstFunc)
    {
        if (firstFunc is null) return "module";
        var dot = firstFunc.IndexOf('.');
        var name = dot >= 0 ? firstFunc[..dot] : firstFunc;
        var sb = new StringBuilder();
        foreach (char c in name) sb.Append(char.IsLetterOrDigit(c) || c == '_' ? c : '_');
        return sb.Length > 0 ? sb.ToString() : "module";
    }

    /// <summary>
    /// Compute a stable hash of the module's compilable content. Covers
    /// every function's raw bytecode, the string table, and the static field
    /// count. Two modules with identical hash produce identical generated code.
    /// </summary>
    private string ComputeModuleHash()
    {
        using var sha = System.Security.Cryptography.SHA256.Create();
        // Hash the string table (used for ldstr / call targets).
        foreach (var s in Mod.Strings)
        {
            var buf = System.Text.Encoding.UTF8.GetBytes(s);
            sha.TransformBlock(buf, 0, buf.Length, null, 0);
        }
        // Hash each compilable function's raw bytecode.
        foreach (var func in Mod.Functions)
        {
            if (!IsCompilable(func)) continue;
            sha.TransformBlock(func.Code, 0, func.Code.Length, null, 0);
        }
        // Include static field count (affects generated field accesses).
        var count = BitConverter.GetBytes(StaticFields.Length);
        sha.TransformBlock(count, 0, count.Length, null, 0);
        sha.TransformFinalBlock(Array.Empty<byte>(), 0, 0);
        return Convert.ToHexStringLower(sha.Hash!);
    }

    private static string CS(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");
    private static string F(int v) => v == int.MinValue ? $"unchecked((int){v})" : v.ToString();
    private static string FF(float v) => v.ToString(System.Globalization.CultureInfo.InvariantCulture);
    private static string FD(double v) => v.ToString("G17", System.Globalization.CultureInfo.InvariantCulture);

    private static int ByteSize(ushort op)
    {
        var o = (Opcode)op;
        int table = op / 256;
        int oper = o switch
        {
            Opcode.Nop or Opcode.Add or Opcode.Sub or Opcode.Mul or Opcode.Div or Opcode.Rem or Opcode.Neg
                or Opcode.Ceq or Opcode.Cne or Opcode.Cgt or Opcode.Cge or Opcode.Clt or Opcode.Cle
                or Opcode.And or Opcode.Xor or Opcode.Or or Opcode.Not or Opcode.Dup or Opcode.Pop
                or Opcode.Ldnull or Opcode.Ret or Opcode.Break or Opcode.Continue or Opcode.Throw
                or Opcode.Ldelem or Opcode.Stelem => 0,
            Opcode.LdcI4 or Opcode.Ldc or Opcode.LdcR4 => 4,
            Opcode.LdcI8 or Opcode.LdcR8 => 8,
            Opcode.Ldstr or Opcode.Ldarg or Opcode.Starg or Opcode.Ldloc or Opcode.Stloc
                or Opcode.Ldfld or Opcode.Stfld or Opcode.Ldsfld or Opcode.Stsfld
                or Opcode.Newobj or Opcode.Newarr or Opcode.Conv or Opcode.Castclass or Opcode.Isinst => 2,
            Opcode.Call or Opcode.Callvirt or Opcode.NativeCall => 4,
            Opcode.Br or Opcode.Brtrue or Opcode.Brfalse => 4,
            _ => 0,
        };
        return 1 + table + oper;
    }

    private static void SkipOperand(byte[] code, ref uint pc, ushort op)
    {
        switch ((Opcode)op)
        {
            case Opcode.LdcI4: case Opcode.Ldc: case Opcode.LdcR4: Interpreter.ReadI32(code, ref pc); break;
            case Opcode.LdcI8: case Opcode.LdcR8: Interpreter.ReadI64(code, ref pc); break;
            case Opcode.Ldstr: case Opcode.Ldarg: case Opcode.Starg: case Opcode.Ldloc: case Opcode.Stloc:
            case Opcode.Ldfld: case Opcode.Stfld: case Opcode.Ldsfld: case Opcode.Stsfld:
            case Opcode.Newobj: case Opcode.Newarr: case Opcode.Conv: case Opcode.Castclass: case Opcode.Isinst:
                Interpreter.ReadU16(code, ref pc); break;
            case Opcode.Call: case Opcode.Callvirt: case Opcode.NativeCall: Interpreter.ReadU16(code, ref pc); Interpreter.ReadU16(code, ref pc); break;
            case Opcode.Br: case Opcode.Brtrue: case Opcode.Brfalse: Interpreter.ReadI32(code, ref pc); break;
            // If/While: condition-kind byte, then optional comparison byte or embedded bytecode block.
            case Opcode.If: case Opcode.While:
            {
                byte ck = code[pc++];
                if (ck == 0x01) pc++;                    // Binary comparison byte
                else if (ck >= 0x02)                    // Expression or Block
                {
                    uint len = Interpreter.ReadU32(code, ref pc);
                    pc += len;
                }
                break;
            }
        }
    }
}
