namespace ObjectRT.Abstractions;

/// <summary>
/// Optional hook a binding assembly (or the host runtime) implements to
/// initialize platform-specific state before a bundled module runs.
///
/// Bundle hosts generated by <see cref="ObjectRT.Runtime.BundleDriver"/>
/// construct the <see cref="IHostedRuntime"/>, register binding assemblies,
/// then invoke this setup on every type found in those assemblies that
/// implements it — before the module's entry point executes.
///
/// Example: a UI binding assembly needs its application framework
/// initialized (Avalonia's <c>AppBuilder.SetupWithoutStarting()</c>, a
/// game engine's device, a headless server's config) before any
/// <c>new Window()</c> or equivalent can succeed.
/// </summary>
public interface IHostedRuntimeSetup
{
    /// <summary>Called once before the module runs, with the constructed
    /// runtime (already populated with registered bindings).</summary>
    void Setup(IHostedRuntime runtime);
}
