using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ObjectRT.SourceGenerator;

/// <summary>
/// Roslyn source generator that creates hardwired (reflection-free) dispatch
/// adapters for interfaces marked with [IRHostBinding].
///
/// For each interface like:
/// <code>
/// [IRHostBinding("MonoGame.Screen")]
/// public interface IMonoGameScreen
/// {
///     void Clear(int color);
///     int  Width();
/// }
/// </code>
///
/// it generates an internal static class with one invoker per method:
/// <code>
/// internal static class IMonoGameScreen_ObjectRTDispatch
/// {
///     [ModuleInitializer]
///     internal static void __Register()
///     {
///         global::ObjectRT.Runtime.HostDispatchRegistry.Register(
///             "MonoGame.Screen", "Clear",
///             (object h, object?[] a) => { ((IMonoGameScreen)h).Clear((int)a[0]!); return null; });
///         ...
///     }
/// }
/// </code>
///
/// Dispatch goes through a direct interface cast — no reflection — so host
/// bindings keep working under NativeAOT. Script calls arrive as
/// <c>callnative MonoGame.Screen.Clear(int32)</c>.
/// </summary>
[Generator]
public sealed class HostDispatchGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var interfaceProvider = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) =>
                    node is InterfaceDeclarationSyntax ids && ids.AttributeLists.Count > 0,
                transform: static (ctx, _) =>
                {
                    var ifaceDecl = (InterfaceDeclarationSyntax)ctx.Node;
                    var model = ctx.SemanticModel;
                    var symbol = model.GetDeclaredSymbol(ifaceDecl) as INamedTypeSymbol;

                    if (symbol == null) return null;

                    bool hasBinding = symbol.GetAttributes().Any(a =>
                    {
                        var name = a.AttributeClass?.Name;
                        return name == "IRHostBindingAttribute" ||
                               (name != null && name.EndsWith("IRHostBindingAttribute"));
                    });

                    return hasBinding ? ifaceDecl : null;
                })
            .Where(x => x != null)
            .Collect();

        var combined = context.CompilationProvider.Combine(interfaceProvider);

        context.RegisterSourceOutput(combined, static (spc, source) =>
        {
            var compilation = source.Left;
            var interfaces = source.Right;

            if (interfaces.IsDefaultOrEmpty) return;

            foreach (var iface in interfaces)
            {
                GenerateDispatch(spc, compilation, iface!);
            }
        });
    }

    private static void GenerateDispatch(SourceProductionContext spc, Compilation compilation,
        InterfaceDeclarationSyntax ifaceDecl)
    {
        var model = compilation.GetSemanticModel(ifaceDecl.SyntaxTree);
        var ifaceSymbol = model.GetDeclaredSymbol(ifaceDecl) as INamedTypeSymbol;
        if (ifaceSymbol == null) return;

        var ns = ifaceSymbol.ContainingNamespace.IsGlobalNamespace
            ? ""
            : ifaceSymbol.ContainingNamespace.ToDisplayString();

        var ifaceName = ifaceSymbol.Name;
        var dispatchClassName = $"{ifaceName}_ObjectRTDispatch";
        var ifaceFullName = ifaceSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        // Determine the binding name from [IRHostBinding] attribute
        var bindingName = ifaceName;
        var bindingAttr = ifaceSymbol.GetAttributes().FirstOrDefault(a =>
            a.AttributeClass?.Name is "IRHostBindingAttribute" or "IRHostBinding");

        if (bindingAttr != null &&
            bindingAttr.ConstructorArguments.Length > 0 &&
            bindingAttr.ConstructorArguments[0].Value is string s &&
            !string.IsNullOrEmpty(s))
        {
            bindingName = s;
        }

        // Collect methods
        var methods = ifaceDecl.Members.OfType<MethodDeclarationSyntax>().ToList();
        if (methods.Count == 0) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS8600, CS8601, CS8602, CS8603, CS8604, CS8605, CS8625");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        if (!string.IsNullOrEmpty(ns))
        {
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
        }

        sb.AppendLine($"    internal static class {dispatchClassName}");
        sb.AppendLine("    {");
        sb.AppendLine("        [ModuleInitializer]");
        sb.AppendLine("        internal static void __Register()");
        sb.AppendLine("        {");

        foreach (var method in methods)
        {
            var methodName = method.Identifier.Text;
            var returnType = method.ReturnType.ToString();
            var paramList = method.ParameterList.Parameters;

            // Build the cast expression: ((Iface)(object)h) — direct interface cast.
            var ifaceCast = $"(({ifaceFullName})h)";

            // Argument expressions: (Type)a[i] with element type coercion.
            var argExprs = new List<string>();
            for (int i = 0; i < paramList.Count; i++)
            {
                var pType = paramList[i].Type!.ToString();
                argExprs.Add($"({pType})a[{i}]!");
            }

            var callArgs = string.Join(", ", argExprs);
            var invoke = paramList.Count == 0
                ? $"{ifaceCast}.{methodName}()"
                : $"{ifaceCast}.{methodName}({callArgs})";

            string body;
            if (returnType == "void")
            {
                body = $"{{ {invoke}; return null; }}";
            }
            else
            {
                body = $"{{ return {invoke}; }}";
            }

            sb.AppendLine($"            global::ObjectRT.Runtime.HostDispatchRegistry.Register(");
            sb.AppendLine($"                \"{Escape(bindingName)}\",");
            sb.AppendLine($"                \"{Escape(methodName)}\",");
            sb.AppendLine($"                (object h, object?[] a) => {body});");
            sb.AppendLine();
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        if (!string.IsNullOrEmpty(ns)) sb.AppendLine("}");

        spc.AddSource($"{dispatchClassName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static string Escape(string s) => s.Replace("\"", "\\\"");
}
