using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ObjectRT.SourceGenerator;

/// <summary>
/// Roslyn source generator that creates strongly-typed proxy classes
/// for interfaces marked with [IRClassBinding].
///
/// For each interface like:
/// <code>
/// [IRClassBinding("Calculator")]
/// public interface ICalc {
///     int Add(int a, int b);
/// }
/// </code>
///
/// It generates:
/// <code>
/// internal sealed class ICalc_ObjectRTProxy : ICalc {
///     private readonly IRRuntimeBinding _runtime;
///     public int Add(int a, int b) => _runtime.Invoke&lt;int&gt;("Calculator.Add", a, b);
/// }
/// </code>
///
/// And registers it via [ModuleInitializer] into ProxyRegistry,
/// so Runtime.Bind&lt;ICalc&gt;() returns the proxy with zero reflection overhead.
/// </summary>
[Generator]
public sealed class ProxyGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find interface declarations that have [IRClassBinding] attributes
        var interfaceProvider = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) =>
                    node is InterfaceDeclarationSyntax ids && ids.AttributeLists.Count > 0,
                transform: static (ctx, _) =>
                {
                    var ifaceDecl = (InterfaceDeclarationSyntax)ctx.Node;
                    var model = ctx.SemanticModel;
                    var symbol = model.GetDeclaredSymbol(ifaceDecl) as INamedTypeSymbol;

                    if (symbol == null) return null;

                    bool hasBinding = symbol.GetAttributes().Any(a =>
                    {
                        var name = a.AttributeClass?.Name;
                        return name == "IRClassBindingAttribute" ||
                               (name != null && name.EndsWith("IRClassBindingAttribute"));
                    });

                    return hasBinding ? ifaceDecl : null;
                })
            .Where(x => x != null)
            .Collect();

        var combined = context.CompilationProvider.Combine(interfaceProvider);

        context.RegisterSourceOutput(combined, static (spc, source) =>
        {
            var compilation = source.Left;
            var interfaces = source.Right;

            if (interfaces.IsDefaultOrEmpty) return;

            foreach (var iface in interfaces)
            {
                GenerateProxy(spc, compilation, iface!);
            }
        });
    }

    private static void GenerateProxy(SourceProductionContext spc, Compilation compilation,
        InterfaceDeclarationSyntax ifaceDecl)
    {
        var model = compilation.GetSemanticModel(ifaceDecl.SyntaxTree);
        var ifaceSymbol = model.GetDeclaredSymbol(ifaceDecl) as INamedTypeSymbol;
        if (ifaceSymbol == null) return;

        var ns = ifaceSymbol.ContainingNamespace.IsGlobalNamespace
            ? ""
            : ifaceSymbol.ContainingNamespace.ToDisplayString();

        var ifaceName = ifaceSymbol.Name;
        var proxyClassName = $"{ifaceName}_ObjectRTProxy";
        var ifaceFullName = ifaceSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        // Determine the ObjectRT class name from [IRClassBinding] attribute
        var className = ifaceName;
        var classAttr = ifaceSymbol.GetAttributes().FirstOrDefault(a =>
            a.AttributeClass?.Name is "IRClassBindingAttribute" or "IRClassBinding");

        if (classAttr != null)
        {
            if (classAttr.ConstructorArguments.Length > 0 &&
                classAttr.ConstructorArguments[0].Value is string s && !string.IsNullOrEmpty(s))
                className = s;
        }

        // Collect methods
        var methods = ifaceDecl.Members.OfType<MethodDeclarationSyntax>().ToList();
        if (methods.Count == 0) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#pragma warning disable CS8600, CS8601, CS8603, CS8604, CS8625");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using ObjectRT.Runtime;");
        if (!string.IsNullOrEmpty(ns))
        {
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
        }

        sb.AppendLine($"    internal sealed class {proxyClassName} : {ifaceFullName}");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly IRRuntimeBinding _runtime;");
        sb.AppendLine($"        public {proxyClassName}(IRRuntimeBinding runtime) => _runtime = runtime;");
        sb.AppendLine();

        // [ModuleInitializer] registration
        sb.AppendLine("        [ModuleInitializer]");
        sb.AppendLine($"        internal static void __Register()");
        sb.AppendLine("        {");
        sb.AppendLine($"            global::ObjectRT.Runtime.ProxyRegistry.Register<{ifaceFullName}>(");
        sb.AppendLine($"                rt => new {proxyClassName}(rt));");
        sb.AppendLine("        }");
        sb.AppendLine();

        foreach (var method in methods)
        {
            var methodName = method.Identifier.Text;
            var returnType = method.ReturnType.ToString();
            var paramList = string.Join(", ", method.ParameterList.Parameters.Select(p =>
                $"{p.Type} {p.Identifier}"));
            var argNames = string.Join(", ", method.ParameterList.Parameters.Select(p =>
                p.Identifier.Text));

            // Check for [IRMethodBinding] attribute
            var methodSym = model.GetDeclaredSymbol(method);
            var irMethodName = methodName;
            if (methodSym != null)
            {
                var methodAttr = methodSym.GetAttributes().FirstOrDefault(a =>
                    a.AttributeClass?.Name is "IRMethodBindingAttribute" or "IRMethodBinding");
                if (methodAttr != null &&
                    methodAttr.ConstructorArguments.Length > 0 &&
                    methodAttr.ConstructorArguments[0].Value is string mn &&
                    !string.IsNullOrEmpty(mn))
                    irMethodName = mn;
            }

            sb.AppendLine($"        public {returnType} {methodName}({paramList})");
            sb.AppendLine("        {");

            if (returnType == "void")
            {
                if (method.ParameterList.Parameters.Count == 0)
                    sb.AppendLine($"            _runtime.Invoke<object?>(\"{className}.{irMethodName}\");");
                else
                    sb.AppendLine($"            _runtime.Invoke<object?>(\"{className}.{irMethodName}\", {argNames});");
            }
            else
            {
                if (method.ParameterList.Parameters.Count == 0)
                    sb.AppendLine($"            return _runtime.Invoke<{returnType}>(\"{className}.{irMethodName}\");");
                else
                    sb.AppendLine($"            return _runtime.Invoke<{returnType}>(\"{className}.{irMethodName}\", {argNames});");
            }

            sb.AppendLine("        }");
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        if (!string.IsNullOrEmpty(ns)) sb.AppendLine("}");

        spc.AddSource($"{proxyClassName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
